### PR TITLE
[FEATURE] Orders: Add sequence and flags to account orders (RLJS-181)

### PR DESCRIPTION
**Pull request by lumberj**
- Making this API consistent with https://github.com/ripple/ripple-rest/pull/250

### CODE REVIEW

**Comment by lumberj** [comment]
I'm wondering if this should be updated to be consistent with the [`order object`](https://ripple.com/build/ripple-rest/#order-objects) and the goal of having a static schema for JSON request/response objects. Also, in this case we're using `counterparty` in the `Amount` and not `issuer`, as we talked about using `counterparty` exclusively in ripple-rest. The [docs](https://ripple.com/build/ripple-rest/#amount_object) need to be updated to reflect that.

@boxbag did you update the last remaining places we're using `issuer`?

**Comment by boxbag** [comment]
No, payments is still using `issuer` to my knowledge

**Comment by lumberj** [comment]
I can update `payments` to use `counterparty` and optionally (i.e., deprecate) use `issuer`

**Comment by geertweening** [comment]
LGTM

**Comment by lumberj** [comment]
Rebased

**Pull request merged**
