### PR TITLE
Eliminate unit test coupling due to ledger index

### PR DESCRIPTION
**Pull request by clark800**

### CODE REVIEW

**Comment by lumberj** [comment]
LGTM. How did you get around the address in use error?

**Comment by geertweening** [comment]
LGTM

**Comment by clark800** [comment]
@lumberj The address in use error went away by itself when I did it this way. I'm not sure what it was doing before that caused the error.

**Comment by vinniefalco** [comment]
Good looking commit message. It leaves out the annoying [TASK], [CHORE], etc... labels. It explains the change at a high level. And it explains the motivation behind the change. All commit messages should be more like this one. We don't need commit messages that just mechanically repeat what you can already tell from the diff. For example `Change LastLedgerSequence in orders test fixture` would be accurate, but useless.

**Pull request merged**
