### PR TITLE
Update .travis.yml to use faster docker containers

### PR DESCRIPTION
**Pull request by clark800**
"your builds now start in less than 10 seconds" - http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/

### CODE REVIEW

**Comment by lumberj** [comment]
This may not help much:

> The default behavior when no sudo usage is detected is to send Linux builds to this infrastructure. 

http://docs.travis-ci.com/user/workers/container-based-infrastructure/

**Comment by lumberj** [comment]
Another thing we can do is run the linting and testing in parallel, or run many tests in parallel

**Comment by clark800** [comment]
It takes 5-10 minutes to start quite frequently, so if their 10 second statistic is anywhere near valid, then maybe it wasn't able to determine that sudo wasn't used. Linting only takes a few seconds and the unit tests only take about 12 seconds, so these aren't a big issue. Also, some of the unit tests are not parallelizable currently. For example, the ones that use `withDeterministicPRNG` override the global SJCL random number generator and could get different answers if they ran concurrently.

**Comment by clark800** [comment]
This did have an effect. Looking at the travis build logs, they are now running on `worker-linux-docker-*` whereas before they were running on `worker-linux-*`.

**Pull request merged**
