### PR TITLE
[FIX] do not allow duplicate client_resource_id

### PR DESCRIPTION
**Pull request by geertweening**
even if the transaction failed

### CODE REVIEW

**Comment by lumberj** [comment]
We don't have any tests that cover this stuff? This is a breaking API change, even though the current behavior may not be documented

**Comment by lumberj** [comment]
Otherwise LGTM, we should add this to documentation though

**Comment by geertweening** [comment]
Good point. I'll add a test and I created a separate task to update the docs

**Comment by geertweening** [comment]
updated with tests

**Comment by lumberj** [comment]
LGTM

**Pull request merged**
