### PR TITLE
[FEATURE] Use gzip compression

### PR DESCRIPTION
**Pull request by lumberj**

### CODE REVIEW

**Comment by clark800** [comment]
Nice

**Comment by wltsmrz** [comment]
Now that we have paging trustlines, etc., are we going to gain very much here? Compressing and decompressing comes at a cost to the server and clients. I don't think curl will automatically decompress either (specify --compressed). Does Node's HTTP client automatically decompress? Do most popular HTTP clients? Can you give an example of a large JSON response w/ bytes saved?

**Comment by lumberj** [comment]
I'll try to address each question. For an example where bytes are saved, consider the order_book API which cannot be paged:

`GET http://localhost:5990/v1/accounts/rQE5Z3FgVnRMbVfS6xiVQFgB4J3X162FVD/order_book/BTC+rvYAfWj5gh67oV6fW32ZzP3Aw4Eubs59B/USD+rvYAfWj5gh67oV6fW32ZzP3Aw4Eubs59B`

Without gzip:
image

With gzip:
image

**Comment by lumberj** [comment]
> Compressing and decompressing comes at a cost to the server and clients.

The client does not have to send the gzip headers

**Comment by wltsmrz** [comment]
The client has to decompress...

**Comment by lumberj** [comment]
Node's `http` client does not automatically handle gzip compression. See [this](http://nodejs.org/docs/v0.6.0/api/zlib.html#examples) for an example of using the `zlib` library to handle this.

**Comment by lumberj** [comment]
The `compression` library supports a setting to only gzip at a certain threshold. The default is 1kB. We can increase this.

**Comment by wltsmrz** [comment]
In my experience, gzipping will come at a fairly large cost in Node, but it's been a while since I ran serious benchmarks. I kind of prefer not requiring clients to gunzip; it's just JSON after all. rippled doesn't gzip and it could probably do so more efficiently than in Node.

**Comment by lumberj** [comment]
Unless clients specifically request compression, they won't get gzipped responses. This is not the default in node as the example I linked to shows:

```javascript
var request = http.get({ host: 'izs.me',
                         path: '/',
                         port: 80,
                         headers: { 'accept-encoding': 'gzip,deflate' } });
```

**Comment by wltsmrz** [comment]
Oh, so this "compression" library respects accept-encoding. Hrm. I see what you were saying now.

**Comment by wltsmrz** [comment]
LGTM, I think

**Comment by lumberj** [comment]
Sorry, should have made it more clear. The compression library is designed to be used with `express` and handle requests correctly.

**Comment by wltsmrz** [comment]
It can be considered "correct" for the server to send whatever it has, with the appropriate response headers, and for the client to respect those headers or otherwise *deal with it*. Since this middleware respects accept-encoding I'm less concerned about various client defaults.

**Comment by geertweening** [comment]
Nice, LGTM

**Pull request merged**
